# THIS IS THE DEFAULT CONFIG
#
#
# Change the value of the node below to the folder you want to copy world files from.
# If not specified, or non-existant, or the same as Bukkit's default world, the plugin will shutdown
world-to-reset: world
reset-no-people: false
reload-translations: true
translation: en