name: Map Reset
version: 0.2
main: li.maxsa.java.mapreset.MapReset
author: msalihov
description: The map that is configured in the configuration file is reset on command
commands:
  resetworld:
    description: Resets a map to the one set in config
    usage: /<command>
    aliases: [rw, resetw, rworld]
    permission: mapreset.reset
permissions:
  mapreset.reset:
    description: Allows user to reset a map
    default: op